FileVersion = 1

[Project]
Name = "libxml2-beef"
DefaultNamespace = "libxml2"
ProcessorMacros = ["LIBXML_C14N_ENABLED", "LIBXML_CATALOG_ENABLED", "LIBXML_DEBUG_ENABLED", "LIBXML_HTML_ENABLED", "LIBXML_HTTP_ENABLED", "LIBXML_ICONV_ENABLED", "LIBXML_LEGACY_ENABLED", "LIBXML_MODULES_ENABLED", "LIBXML_OUTPUT_ENABLED", "LIBXML_PATTERN_ENABLED", "LIBXML_PUSH_ENABLED", "LIBXML_READER_ENABLED", "LIBXML_REGEXP_ENABLED", "LIBXML_SAX1_ENABLED", "LIBXML_SCHEMAS_ENABLED", "LIBXML_SCHEMATRON_ENABLED", "LIBXML_THREAD_ALLOC_ENABLED", "LIBXML_THREAD_ENABLED", "LIBXML_UNICODE_ENABLED", "LIBXML_VALID_ENABLED", "LIBXML_WRITER_ENABLED", "LIBXML_XINCLUDE_ENABLED", "LIBXML_XPATH_ENABLED", "LIBXML_XPTR_ENABLED"]

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\debug\\libxml2sd.lib", "bcrypt.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\libxml2s.lib"]
